### ISSUE TITLE
All syslogs gets the same level (Warning)

### ISSUE THREAD

**Issue by gribber** [mib1185/ha-addon-syslog#5]
Seems like every syslog message gets the "Warning" level

Using Log Center in my Synology NAS as server, no matter what I do, everything seems to get the same severity

![image](https://github.com/user-attachments/assets/cd7e0f42-991a-41c4-84a0-e023b208199c)

Neither BSD or IEFT format works and by looking a earlier pull request, I can see there is a merge that should make it rfc3164 (BSD) compliant

Am I missing something out here?

**Comment by mib1185** [comment]
This add-on reads the messages from the systemd journal service, which unfortunately not set a proper `priority` tag to its messages (_the origin level get lost somewhere between the python logging within the containers, the docker daemon and the journal service in the HAOS_)
Maybe a parsing for at least the `homeassistant` container could be implemented, but for all other addons (_containers_) the log format  is not ensured

**Comment by gribber** [comment]
Ok I see, 
what about a way to add custom (regex)parsing for matching containers, like:
homeassistant -> <timestamp> <level> <msg>
addon_xyz -> <other timestamp format> <junk> <level> <msg>

**Comment by mib1185** [comment]
With #6 (_version [0.2.0](https://github.com/mib1185/ha-addon-syslog/releases/tag/v0.2.0) of this addon_) the correct syslog level will now be determined for ha core, supervisor and haos host messages. Further the default for un-determined messages is now set to info, instead of warning.

I'm still thinking about the suggestion of custom regex parsing possibilities :thinking:

**Comment by gribber** [comment]
awesome, I'll give it a try, thanks for the quick response!
